### ISSUE TITLE
Uncaught TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.

### ISSUE THREAD

**Issue by mattgraham** [spiehler/language-chordpro#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.2
**Thrown From**: [language-chordpro](https://github.com/spiehler/language-chordpro) package 0.2.3

### Stack Trace

Uncaught TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.

```
At /Users/mattgraham/.atom/packages/language-chordpro/lib/language-chordpro-view.js:58

TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.
    at LanguageChordproView.addChords (/packages/language-chordpro/lib/language-chordpro-view.js:58:20)
    at /packages/language-chordpro/lib/language-chordpro-view.js:25:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:263:18)
    at Pane.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:1018:46)
    at Pane.focus (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -1:23.8.0 core:paste (input.hidden-input)
  5x -1:23.4.0 core:move-up (input.hidden-input)
     -1:22.1.0 core:move-down (input.hidden-input)
     -1:21.3.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:20.8.0 core:backspace (input.hidden-input)
     -1:20.3.0 core:move-down (input.hidden-input)
  3x -1:20.1.0 core:select-right (input.hidden-input)
     -1:18.9.0 core:backspace (input.hidden-input)
  6x -1:18.5.0 core:move-right (input.hidden-input)
  7x -1:17.2.0 core:select-right (input.hidden-input)
  2x -1:16 core:copy (input.hidden-input)
  2x -1:15.3.0 core:backspace (input.hidden-input)
     -1:13.4.0 core:move-to-bottom (input.hidden-input)
     -1:07.9.0 core:backspace (input.hidden-input)
     -0:46.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:45 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ember-cli-helper 0.9.0 
emmet 2.4.3 
git-plus 7.8.0 
language-chordpro 0.2.3 
Zen 0.18.0 
```

**Comment by spiehler** [comment]
I am still working on the Helper functions. This bug is fixed in the latest version. More to come in the next days ...
